set sysconfdir and localstatedir, add with-peruserlimits
instrumentisto/pure-ftpd-docker-image pull request #7
Opened 2024-08-28 14:59 UTC by matthewh86

hi, thanks for the base image!

this separates out the configuration from the image's `/etc` and `/var` locations to allow for simpler volume mounting (e.g. for persisting configuration and user accounts).

this also adds with-peruserlimits to support the PER_USER_LIMITS property that is useful for allowing more than 20 anonymous connections

2024-08-28 16:47 UTC, tyranron requested changes
@matthewh86 thanks for the PR!

I'm not against `--withperuserlimits` and `--localstatedir=/var/pure-ftpd`.

However, I would like not to change `--sysconfdir=/etc/pure-ftpd` since it would break existing installations using default paths quite hard. You still can mount anything in one dir just by specifying custom paths as described in README.

Also, I wonder: why would you want to mount `/var/pure-ftpd`?

2024-08-28 21:52 UTC, matthewh86 commented
`--sysconfdir=/etc/pure-ftpd` - I'll revert and just add config to my dependant image.

Regarding the pid question for `--localstatedir=/var/pure-ftpd`, I have no real answer to thas, so I can just revert it.

2024-08-28 22:11 UTC, matthewh86 commented
In case you were interested, here's the docker image I spent _way_ too long fighting with to get to state where I'm mostly happy with how it functions.

https://github.com/noxtech/anonymous-pure-ftp

- Anonymous user support
- Virtual "standard" user support
- Virtual "super" user support

Things which gave me a headache were how docker mounts volumes, screws with the file/directory permissions and ownership, and various other quirks that I've forgotten about.

2024-08-29 14:29 UTC, tyranron commented
> Things which gave me a headache were how docker mounts volumes, screws with the file/directory permissions and ownership, and various other quirks that I've forgotten about.

Yeah... it's better on Kubernetes. But Docker Compose may give some headache here.

Nevertheless, the image comes with `s6-overlay` system included, so everything you've done in your Docker image could be just a mounted `s6` startup script without a need for the derivated image. However, given the circumstances, it may be not so pleasant to deploy (again, in Kubernetes it's quite easy).

2024-08-29 14:32 UTC, tyranron approved these changes

2024-08-29 14:34 UTC, merged

2024-08-29 14:41 UTC, tyranron commented
Released as [1.0.51-r28](https://github.com/instrumentisto/pure-ftpd-docker-image/releases/tag/1.0.51-r28).